
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.weather;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621107
 * 2017-02-22T22:57:30.052-05:00
 * Generated source version: 3.0.4.redhat-621107
 * 
 */

@javax.jws.WebService(
                      serviceName = "StockQuote",
                      portName = "StockQuoteHttpPost",
                      targetNamespace = "http://www.webserviceX.NET/",
                      wsdlLocation = "http://www.webservicex.net/stockquote.asmx?WSDL",
                      endpointInterface = "com.weather.StockQuoteHttpPost")
                      
public class StockQuoteHttpPostImpl implements StockQuoteHttpPost {

    private static final Logger LOG = Logger.getLogger(StockQuoteHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see com.weather.StockQuoteHttpPost#getQuote(java.lang.String  symbol )*
     */
    public java.lang.String getQuote(java.lang.String symbol) { 
        LOG.info("Executing operation getQuote");
        System.out.println(symbol);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
